buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.palantir.gradle.jdks:gradle-jdks:0.82.0'
        classpath 'com.palantir.gradle.jdkslatest:gradle-jdks-latest:0.32.0'
        // Purposefully staying on this old version of baseline, going above 6.0.0 requires all tooling to be JDK 17+ and gradle-jdks only supports 11 OR 21+
        classpath 'com.palantir.baseline:gradle-baseline-java:5.72.0'
        classpath 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin:1.37.0'
        classpath 'com.palantir.gradle.failure-reports:gradle-failure-reports:1.20.0'
        classpath 'com.palantir.gradle.idea-configuration:gradle-idea-configuration:0.11.0'
        classpath 'com.palantir.javaformat:gradle-palantir-java-format:2.72.0' // Bumping beyond requires JDK 17, due to spotless 3.0
    }
}

plugins {
    id 'java'
    id 'com.github.ben-manes.versions' version '0.53.0'
    id 'com.palantir.git-version' version '5.0.0'
    id 'com.autonomousapps.dependency-analysis' version '3.6.1'
    id 'de.undercouch.download' version '5.7.0'
}

apply plugin: 'com.palantir.external-publish-jar'
apply plugin: 'com.palantir.jdks'
apply plugin: 'com.palantir.baseline'
apply plugin: 'com.palantir.baseline-checkstyle'
apply plugin: 'com.palantir.baseline-config'
apply plugin: 'com.palantir.baseline-error-prone'
apply plugin: 'com.palantir.baseline-idea'
apply plugin: 'com.palantir.baseline-java-versions'
apply plugin: 'com.palantir.failure-reports'
apply plugin: 'com.palantir.java-format'
apply plugin: 'com.palantir.jdks.latest'

group = 'com.palantir.isofilereader'
version gitVersion()
description = 'A Java library to natively read ISO-9660 and UDF files'

// Needed if baselineUpdateConfig is added to the build command
// checkstyleMain.dependsOn baselineUpdateConfig
// checkstyleTest.dependsOn baselineUpdateConfig

// dependencyUpdate Related
def isNonStable = { String version ->
    def stableKeyword = ['RELEASE', 'FINAL', 'GA'].any { it -> version.toUpperCase().contains(it) }
    def regex = /^[0-9,.v-]+(-r)?$/
    return !stableKeyword && !(version ==~ regex)
}

dependencyUpdates {
    rejectVersionIf {
        isNonStable(it.candidate.version)
    }
}

repositories {
    mavenCentral() { metadataSources { mavenPom(); ignoreGradleMetadataRedirection() } }
}

test {
    minHeapSize = "256m" // initial heap size
    maxHeapSize = "4096m" // maximum heap size

    useJUnitPlatform()
    exclude '**/IsoImageTestsLargeIso.java'
    exclude '**/OneOffTests.java'
}

// Download ISO to test against
def isoProps = new Properties()
file("isos.props").withInputStream { isoProps.load(it) }

def isos = ['rocky', 'ubuntu', 'windows']
isos.each { name ->
    tasks.register("download${name.capitalize()}ForTestingIfNotPresent", Download) {
        src isoProps["${name}.url"]
        dest new File("${projectDir}/test_isos/", "${name}.iso")
        overwrite false
        onlyIfModified true
        retries 5
        connectTimeout 30000
        readTimeout 600000

        // Download to temp file first, then move on success
        // This prevents partial files from being left behind
        tempAndMove true
        // There are multiple workers, you know in circle the job is done when you see a verify task
    }

    tasks.register("verify${name.capitalize()}File", Verify) {
        dependsOn "download${name.capitalize()}ForTestingIfNotPresent"
        src "${projectDir}/test_isos/${name}.iso"
        algorithm 'SHA256'
        checksum isoProps["${name}.checksum"]
    }
}

test.dependsOn(isos.collect { "verify${it.capitalize()}File" })

// Publishing and dependencies

publishMavenPublicationToMavenLocal.dependsOn(test)
dependencies {
    testImplementation group: 'com.github.stephenc.java-iso-tools', name: 'loop-fs-iso-impl', version: '2.1.0'
    testImplementation 'javax.xml.bind:jaxb-api:2.3.1'
    // Bumping JUnit requires JDK 17, https://github.com/junit-team/junit-framework/wiki/Upgrading-to-JUnit-6.0
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.11.3'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.11.3'
}

// To accept gradle scans and publish them
if (hasProperty('buildScan')) {
    buildScan {
        termsOfServiceUrl = 'https://gradle.com/terms-of-service'
        termsOfServiceAgree = 'yes'
    }
}

javaVersions {
    libraryTarget = 11
    runtime = 25
}

jdks {
    daemonTarget = 21
}
